### ISSUE TITLE
ga prefix is "used" by https://github.com/junegunn/vim-easy-align

### ISSUE THREAD

**Issue by partounian** [joereynolds/place.vim#10]
I know they are both suggestions and set by the user but maybe we should change the example to "pl" or something?

**Comment by auwsmit** [comment]
I don't think this is necessarily an issue at all. `ga` is just used as an example in the README and comments and is never actually mapped by the plugin.

However, I do think `ga` is a poor example because it doesn't really make any mnemonic sense to me. Maybe `gs` (useless wait command) or `s` (equivalent to `cl`) for "go/send" would be a more sensible example. Ultimately, it's up to the user to decide their mapping, so it's not a big deal either way.

**Comment by joereynolds** [comment]
Agreed, I initially chose `ga` as it was the least 'destructive' key mapping for my workflow.
People can map it to whatever they want, I think for examples, `ga` is fine
